---
- name: Automation Tool
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

#region Variables
  vars:
    credential:
      host: 10.16.96.121
      username: jasonu
      password: A1rwaysNZ2411
      timeout: 120
      port: '22'
#endregion

#region task
  tasks: 
    - name: test task
      juniper_junos_command:
        provider: "{{ credential }}"
        commands:
          - "show access-list"
      register: response

   # - name: print outputs
   #   debug:
   #     var: item.stdout
   #   with_items: "{{response.results}}"

        
#endregion  