---
- name: Get Device Information
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

#region Variables

  vars_prompt:
   - name: username
     prompt: Junos Username
     private: no
   - name: password
     prompt: Junos Password
     private: yes

  vars:
    connection_info:
      host: "{{ ansible_ssh_host }}" #'10.16.96.121'
      port: '22'
      username: "{{ username }}"
      password: "{{ password }}"
      ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"  #SHA256:BWrXpEtWBd9rK/O8itja76sg1H5iNSw7l2hFr1Q9AIw
#endregion

#region task
  tasks: 
    - name: test task
      juniper_junos_command:
        provider: "{{ connection_info }}"
        commands:
          - "show access-list"
      register: output

    - name: print outputs
      debug:
        var: output
      # with_items: "{{response.results}}"

        
#endregion  