---
- name: Get Device Information
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

#region Variables

  vars_prompt:
   - name: username
     prompt: Junos Username
     private: no
   - name: password
     prompt: Junos Password
     private: yes

  vars:
    connection_info:
      host: '10.16.96.121'
      port: '22'
      username: "{{ username }}"
      password: "{{ password }}"
      ssh_private_key_file: SHA256:dw5XE4AS18xijatseiznvJpStHXLGC6MrF0CniX+kzg jasonu@lab-noc-scr01
#endregion

#region task
  tasks: 
    - name: test task
      juniper_junos_command:
        provider: "{{ connection_info }}"
        commands:
          - "show access-list"
      register: output

    - name: print outputs
      debug:
        var: output
      # with_items: "{{response.results}}"

        
#endregion  