---
- name: Get Device Information
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

#region Variables

  vars_prompt:
   - name: username
     prompt: Junos Username
     private: no
   - name: password
     prompt: Junos Password
     private: yes

  vars:
    credentials:
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 120
      port: '22'
#endregion

#region task
  tasks: 
    - name: test task
      juniper_junos_command:
        provider: "{{ credentials }}"
        commands:
          - "show access-list"
      register: output

    - name: print outputs
      debug:
        var: output
      # with_items: "{{response.results}}"

        
#endregion  