---
- name: Automation Tool
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

#region Variables

  #vars_prompt:
  #  - name: username
  #    prompt: Junos Username
  #    private: no
  #  - name: password
  #    prompt: Junos Password
  #    private: yes

  vars:
    credentials:
      host: 10.16.96.121
      username: jasonu #"{{ username }}"
      password: A1rwaysNZ2411 #"{{ password }}"
      timeout: 120
      port: '22'
      ssh_private_key_file: 'SHA256:BWrXpEtWBd9rK/O8itja76sg1H5iNSw7l2hFr1Q9AIw'
#endregion

#region task
  tasks: 
    - name: test task
      juniper_junos_command:
        provider: "{{ credentials }}"
        commands:
          - "show access-list"
      register: response

   # - name: print outputs
   #   debug:
   #     var: item.stdout
   #   with_items: "{{response.results}}"

        
#endregion  